Accuracy = "Accuracy"
Coodinate = "Coodinate"
count = "Count"
getLatest = "Get Latest Image"
labelMode = "Color Setting"
labelTempSize = "Template is not set"
loadTemplate = "Load Template Image"
openSetting = "Setting"
saveSelectArea = "Save Select Area"
Threshold = "Threshold"
saveTemplate = "Do you want to use the saved image as a template?"
loadImageError = "The image size is not 1280x720 \nPlease select the correct image."