Accuracy = "Accuracy"
Coodinate = "Coodinate"
count = "Count"
getLatest = "Get Latest Image"
labelMode = "Color Setting"
labelTempSize = "Template is not set"
loadTemplate = "Load Template Image"
openSetting = "Setting"
saveSelectArea = "Save Select Area"
Threshold = "Threshold"
