Accuracy = "一致率"
Coodinate = "座標"
count = "カウント"
getLatest = "フォルダ内の最新画像を取得"
labelMode = "色設定"
labelTempSize = "テンプレート画像未設定"
loadTemplate = "テンプレート画像読込"
openSetting = "設定"
saveSelectArea = "選択範囲を保存"
Threshold = "閾値"
saveTemplate = "保存された画像をテンプレートとして使用しますか？"
loadImageError = "画像のサイズが1280x720ではありません。\n正しい画像を選択してください。"
